### ISSUE TITLE
Chicken piccata: pasta should be cooked later

### ISSUE THREAD

**Issue by AlexLamson** [MichelleWellman/Shells-Kitchen#1]
Water should be ready early, but pasta should be cooked nearly last

**Comment by MichelleWellman** [comment]
I wrote that the water should be heated up while the chicken is cooking, and to start cooking the pasta right before making the sauce (they take around the same amount of time). 
Alternatively, we could cook the pasta as the last step and have the chicken sit in the sauce while it's cooking.
